### ISSUE TITLE
Support for i2c interface?

### ISSUE THREAD

**Issue by colesnicov** [rhelmus/virtmem#2]
If you can added support for **i2c** interface rams like e.g. "_24C16A-FRAM_"?

**Comment by rhelmus** [comment]
It has been a while since I worked on this project, but if memory serves me right I2C chips are (were?) much slower than SPI and I didn't considered supporting them for this reason. Still, it's fairly easy to make your own allocator. For instance, see the SPI version (spiram_alloc.h): http://rhelmus.github.io/virtmem/spiram__alloc_8h_source.html
